# Common workflow with a sequence of jobs
name: Main CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This job versionates documentation websites
  versionate_docs:
    name: Versionate docs
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up Node version
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      # Setup root and bootstrap modules
      - name: Setup packages
        run: |
          npm ci
          npx lerna bootstrap

      # Checks an commit log and builds docs with a specific version
      - name: Versionate documentation
        id: versionate_packages
        uses: ./actions/versionate-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Branch name will be used in next commit
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Commit made changes
      - name: Commit & Push changes
        if: github.event_name != 'pull_request'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: Update `versionsArchive.json` [skip ci]'
          branch: ${{ steps.extract_branch.outputs.branch }}
          author_name: SberDevices Frontend Team
          author_email: sberdevices.frontend@gmail.com
  
  # This job calculates changes, releases packages and commits changes if needed
  publish:
    name: Publish
    runs-on: ubuntu-latest
    # Versionate must be ran before version increment 
    needs: versionate_docs
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Git status
      - name: Git status
        run: git status

  # Build current documentation
  documentation:
    name: Documentation build
    runs-on: ubuntu-latest
    # Documentation builds with incremented version
    needs: publish
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Git log
      - name: Git log
        run: |
          git log
          cat ./website/plasma-ui-docs/versionsArchived.json
